{
 "title": "Amazon RDS / Aurora MySQL  Metrics",
 "tags": [
  "Percona",
  "Cloud"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "instance",
    "label": "DB Instance",
    "query": "dimension_values($region,AWS/RDS,CPUUtilization,DBInstanceIdentifier)"
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Engine Uptime",
   "type": "singlestat",
   "description": "The amount of time that the instance has been running.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "alias": "Engine Uptime",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "EngineUptime",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "CPU Utilization",
   "type": "singlestat",
   "description": "The percentage of CPU used by an Aurora MySQL DB instance.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Current QPS",
   "type": "singlestat",
   "description": "The average number of queries executed per second.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "alias": "QPS",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "Queries",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "FreeableMemory",
   "type": "singlestat",
   "description": "The amount of available random access memory, in bytes.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "alias": "Engine Uptime",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Cost",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 6 },
     "content": "Amazon provides 1 million CloudWatch API requests each month at no additional charge. Past this, it costs $0.01 per 1,000 requests. This dashboard does 15 requests on each refresh."
    }
   ]
  },
  { "title": "CPU", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU Utilization",
   "type": "graph",
   "description": "The percentage of CPU used by an Aurora MySQL DB instance.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "CPU",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "CPU Credit Usage",
   "type": "graph",
   "description": "`CPUCreditBalance /  Credits Accumulated ` - \nThe number of CPU credits that an instance has accumulated. This metric applies only to db.t2.small and db.t2.medium instances. It's used to determine how long an Aurora MySQL DB instance can burst beyond its baseline performance level at a given rate.\n\n`CPUCreditUsage / Credits Consumed` - \nThe number of CPU credits consumed during the specified period. This metric applies only to db.t2.small and db.t2.medium instances. It identifies the amount of time during which physical CPUs have been used for processing instructions by virtual CPUs allocated to the Aurora MySQL DB instance.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Credits Accumulated",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "CPUCreditBalance",
     "namespace": "AWS/RDS",
     "period": "300",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "Credits Consumed",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "CPUCreditUsage",
     "namespace": "AWS/RDS",
     "period": "300",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "New row", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Network Traffic",
   "type": "graph",
   "description": "`NetworkReceiveThroughput` - \nThe amount of network throughput received from clients by each instance in the Aurora MySQL DB cluster, in bytes per second. This throughput doesn't include network traffic between instances in the Aurora MySQL DB cluster and the cluster volume.\n\n`NetworkThroughput` - \nThe amount of network throughput both received from and transmitted to clients by each instance in the Aurora MySQL DB cluster, in bytes per second. This throughput doesn't include network traffic between instances in the DB cluster and the cluster volume.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Inbound",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "NetworkReceiveThroughput",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "Outbound",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "NetworkTransmitThroughput",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "description": "The amount of available random access memory, in bytes.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Available",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "FreeableMemory",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "Aurora MySQL Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Active / Blocked Transactions",
   "type": "graph",
   "description": "`ActiveTransactions` - \nThe average number of current transactions executing on an Aurora MySQL DB instance per second.\n\n`BlockedTransactions` - \nThe average number of transactions in the database that are blocked per second.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Active Transactions",
     "dimensions": { "DBClusterIdentifier": "$instance" },
     "metricName": "ActiveTransactions",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "Blocked Transactions",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "BlockedTransactions",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Database Connections",
   "type": "graph",
   "description": "The number of connections to an Aurora MySQL DB instance.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Database Connections",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "DatabaseConnections",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Replication Statistics",
   "type": "graph",
   "description": "`Aurora Replica Lag` - \nFor an Aurora MySQL Replica, the amount of lag when replicating updates from the primary instance, in milliseconds.\n\n`AuroraBinlogReplicaLag` - \nThe amount of time an Aurora MySQL DB cluster lags behind the source DB cluster.\n\nThis metric reports the value of the Seconds_Behind_Master field of the MySQL SHOW SLAVE STATUS command and is useful for monitoring replica lag between Aurora DB clusters that are replicating across different AWS regions.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Aurora Replica Lag",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "AuroraReplicaLag",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "Aurora Binlog Replica Lag",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "AuroraBinlogReplicaLag",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "DML / DDL Throughput",
   "type": "graph",
   "description": "`DMLThroughput` - \nThe average number of inserts, updates, and deletes per second.\n\n`DDLThroughput` - \nThe average number of DDL requests per second.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "alias": "Inserts / updates / deletes per second",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "DMLThroughput",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "DDL requests per second",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "DDLThroughput",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "Disk", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Disk Operations",
   "type": "graph",
   "description": "`ReadIOPS` - \nThe average number of disk I/O operations per second.\n\n`WriteIOPS` - \nThe average number of disk I/O operations per second.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "alias": "Read",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "ReadIOPS",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "Write",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "WriteIOPS",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Disk Latency",
   "type": "graph",
   "description": "`ReadLatency` - \nThe average amount of time taken per disk I/O operation.\n\n`WriteLatency`  - \nThe average amount of time taken per disk I/O operation.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "alias": "Read",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "ReadLatency",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "Write",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "WriteLatency",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Disk Queue Depth",
   "type": "graph",
   "description": "The number of outstanding read/write requests waiting to access the disk.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Outstanding IO Requests",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "DiskQueueDepth",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "graph",
   "description": "`ReadThroughput` - \nThe average number of bytes read from disk per second.\n\n`WriteThroughput` - \nThe average number of bytes written to disk per second.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Read",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "ReadThroughput",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "Write",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "WriteThroughput",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  { "title": "Storage Space and Swap Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Storage Space",
   "type": "graph",
   "description": "The amount of storage available for temporary tables and logs, in bytes.\n\nUnlike for other DB engines, for Aurora MySQL this metric reports the amount of storage available to each DB instance for temporary tables and logs. This value depends on the DB instance class . \nYou can increase the amount of free storage space for an instance by choosing a larger DB instance class for your instance.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Available",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "FreeStorageSpace",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Swap Usage",
   "type": "graph",
   "description": "The amount of swap space used on the Aurora DB instance.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "Used",
     "dimensions": { "DBInstanceIdentifier": "$instance" },
     "metricName": "SwapUsage",
     "namespace": "AWS/RDS",
     "period": "60",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Help",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 },
   "collapsed": true,
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 },
     "content": "# Setup\n\nAdd CloudWatch datasource to Grafana with the name `CloudWatch`.\n\nCreate IAM user and attach the managed policy `CloudWatchReadOnlyAccess`. Then put the credentials in the file `~grafana/.aws/credentials`:\n```\n[default]\naws_access_key_id = youraccesskeyid\naws_secret_access_key = yoursecretaccesskey\n```"
    }
   ]
  },
  { "title": "Copyrights & Legal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "type": "text",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 62 },
   "content": "<center >\n  <p>MySQL and InnoDB are trademarks of Oracle Corp. Proudly running Percona Server. Copyright © 2006-2018 Percona LLC.</p>\n  <div style=\"text-align:center;\">\n    <a href=\"https://percona.com/terms-use\" style=\"display: inline;\">Terms of Use</a> | \n    <a href=\"https://percona.com/privacy-policy\" style=\"display: inline;\">Privacy</a> | \n    <a href=\"https://percona.com/copyright-policy\" style=\"display: inline;\">Copyright</a> | \n    <a href=\"https://percona.com/legal\" style=\"display: inline;\">Legal</a>\n  </div>\n</center>\n<hr>\n<link rel=\"stylesheet\" type=\"text/css\" href=\"//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css\" />\n<script src=\"//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js\"></script>\n<script>\nfunction bbb(){\n  \n  setTimeout(function (){ \n  window.cookieconsent.initialise({\n    \"palette\": {\n      \"popup\": {\n        \"background\": \"#eb6c44\",\n        \"text\": \"#ffffff\"\n      },\n      \"button\": {\n        \"background\": \"#f5d948\"\n      }\n    },\n    \"theme\": \"classic\",\n    \"content\": {\n      \"message\": \"This site uses cookies and other tracking technologies to assist with navigation, analyze your use of our products and services, assist with promotional and marketing efforts, allow you to give feedback, and provide content from third parties. If you do not want to accept cookies, adjust your browse\",\n      \"dismiss\": \"Allow cookies\",\n      \"link\": \"Cookie Policy\",\n      \"href\": \"https://www.percona.com/cookie-policy\"\n    }\n  })},3000)};\n  \n  \n  window.addEventListener(\"load\",bbb());\n\n\n\n</script>"
  }
 ]
}