{
 "title": "CPU Utilization Details (Cores)",
 "tags": [
  "Percona",
  "OS"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values({__name__=~\"node_cpu|node_cpu_average\", job!=\"prometheus\"}, instance)"
   },
   {
    "name": "cpu",
    "label": "CPU",
    "query": "label_values(node_cpu{instance=\"$host\"}, cpu)"
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "$host - Overall CPU Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host\",mode!=\"idle\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",mode!=\"idle\"}[5m]),1)) ))*100 or (max_over_time(node_cpu_average{instance=~\"$host\", mode!=\"total\", mode!=\"idle\"}[$interval]) or max_over_time(node_cpu_average{instance=~\"$host\", mode!=\"total\", mode!=\"idle\"}[5m]))),100)",
     "legendFormat": "{{mode}}"
    },
    {
     "expr": "clamp_max(max by () ((sum  by (cpu) ( (clamp_max(rate(node_cpu{instance=\"$host\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )*100) or (max_over_time(node_cpu_average{instance=~\"$host\", mode!=\"total\", mode!=\"idle\", mode!=\"wait\"}[$interval]) or max_over_time(node_cpu_average{instance=~\"$host\", mode!=\"total\",mode!=\"idle\", mode!=\"wait\"}[5m]))),100)",
     "legendFormat": "Max Core Utilization"
    }
   ]
  },
  {
   "title": "$host - Current CPU Core Utilization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "clamp_max(avg by () ((sum by (cpu) ( (clamp_max(irate(node_cpu{instance=\"$host\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1))*100 )) or max_over_time(node_cpu_average{instance=~\"$host\", mode!=\"total\",mode!=\"idle\", mode!=\"wait\"}[5m])) ,100)",
     "legendFormat": "Avg"
    },
    {
     "calculatedInterval": "2s",
     "expr": "clamp_max((sum by (cpu) ( (clamp_max(irate(node_cpu{instance=\"$host\",mode!=\"idle\",mode!=\"iowait\"}[5m])*100,100)) )) or sum by (cpu) (max_over_time(node_cpu_average{instance=~\"$host\", mode!=\"total\",mode!=\"idle\", mode!=\"wait\"}[5m])) ,100)",
     "legendFormat": " {{cpu}}"
    }
   ]
  },
  {
   "title": "Overall CPU Utilization Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 }
  },
  {
   "title": "All Cores - total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(sum by () ((avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",cpu=\"$cpu\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )) *100 or (max_over_time(node_cpu_average{instance=~\"$host\", mode=\"total\"}[$interval]) or max_over_time(node_cpu_average{instance=~\"$host\", mode=\"total\"}[5m]))),100)"
    }
   ]
  },
  {
   "title": "All Cores - user",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host\",mode=\"user\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",mode=\"user\"}[5m]),1)) )) *100 or (avg_over_time(node_cpu_average{instance=\"$host\", mode=\"user\"}[$interval]) or avg_over_time(node_cpu_average{instance=\"$host\", mode=\"user\"}[5m]))),100)"
    }
   ]
  },
  {
   "title": "All Cores - system",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host\",mode=\"system\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",mode=\"system\"}[5m]),1)) )) *100 or (avg_over_time(node_cpu_average{instance=\"$host\", mode=\"system\"}[$interval]) or avg_over_time(node_cpu_average{instance=\"$host\", mode=\"system\"}[5m]))),100)"
    }
   ]
  },
  {
   "title": "All Cores - iowait",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host\",mode=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",mode=\"iowait\"}[5m]),1)) )) *100 or (avg_over_time(node_cpu_average{instance=\"$host\", mode=\"wait\"}[$interval]) or avg_over_time(node_cpu_average{instance=\"$host\", mode=\"wait\"}[5m]))),100)"
    }
   ]
  },
  {
   "title": "All Cores - steal",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host\",mode=\"steal\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",mode=\"steal\"}[5m]),1)) )) *100 or (avg_over_time(node_cpu_average{instance=\"$host\", mode=\"steal\"}[$interval]) or avg_over_time(node_cpu_average{instance=\"$host\", mode=\"steal\"}[5m]))),100)"
    }
   ]
  },
  {
   "title": "All Cores - other",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 18 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(((sum by () (avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"steal\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"steal\"}[5m]),1)) )) *100) or (sum(avg_over_time(node_cpu_average{instance=\"$host\", mode!=\"total\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"wait\",mode!=\"steal\"}[$interval])) or sum(avg_over_time(node_cpu_average{instance=\"$host\", mode!=\"total\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"wait\",mode!=\"steal\"}[5m])))),100) "
    }
   ]
  },
  {
   "title": "CPU Cores Utilization Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Per Core CPU Usage",
     "type": "text",
     "gridPos": { "h": 3, "w": 24, "x": 0, "y": 22 },
     "content": "Per CPU usage Information shows  usage for each CPU (Virtual) core.  The Current (most recent) numbers are shown together with history as sparkline"
    }
   ]
  },
  { "title": "$cpu", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 }, "repeat": "cpu" },
  {
   "title": "$cpu - total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max((sum by () ((avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host\",mode!=\"idle\",mode!=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",cpu=\"$cpu\",mode!=\"idle\",mode!=\"iowait\"}[5m]),1)) )) *100) or (max_over_time(node_cpu_average{instance=\"$host\",mode=\"total\"}[$interval]) or max_over_time(node_cpu_average{instance=\"$host\",mode=\"total\"}[5m]))),100)"
    }
   ]
  },
  {
   "title": "$cpu - user",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host\",cpu=\"$cpu\",mode=\"user\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",cpu=\"$cpu\",mode=\"user\"}[5m]),1)) )) *100 or (avg_over_time(node_cpu_average{instance=\"$host\", cpu=\"All\", mode=\"user\"}[$interval]) or avg_over_time(node_cpu_average{instance=\"$host\", cpu=\"All\", mode=\"user\"}[5m]))),100)"
    }
   ]
  },
  {
   "title": "$cpu - system",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host\",cpu=\"$cpu\",mode=\"system\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",cpu=\"$cpu\",mode=\"system\"}[5m]),1)) )) *100 or (avg_over_time(node_cpu_average{instance=\"$host\", cpu=\"All\", mode=\"system\"}[$interval]) or avg_over_time(node_cpu_average{instance=\"$host\", cpu=\"All\", mode=\"system\"}[5m]))),100)"
    }
   ]
  },
  {
   "title": "$cpu - iowait",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host\",cpu=\"$cpu\",mode=\"iowait\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",cpu=\"$cpu\",mode=\"iowait\"}[5m]),1)) )) *100 or (avg_over_time(node_cpu_average{instance=\"$host\", cpu=\"All\", mode=\"wait\"}[$interval]) or avg_over_time(node_cpu_average{instance=\"$host\", cpu=\"All\", mode=\"wait\"}[5m]))),100)"
    }
   ]
  },
  {
   "title": "$cpu - steal",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(((avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host\",cpu=\"$cpu\",mode=\"steal\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",cpu=\"$cpu\",mode=\"steal\"}[5m]),1)) )) *100 or (avg_over_time(node_cpu_average{instance=\"$host\", cpu=\"All\", mode=\"steal\"}[$interval]) or avg_over_time(node_cpu_average{instance=\"$host\", cpu=\"All\", mode=\"steal\"}[5m]))),100)"
    }
   ]
  },
  {
   "title": "$cpu - other",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 23 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "clamp_max(((sum by (instance) (avg by (mode) ( (clamp_max(rate(node_cpu{instance=\"$host\",cpu=\"$cpu\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"steal\"}[$interval]),1)) or (clamp_max(irate(node_cpu{instance=\"$host\",cpu=\"$cpu\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"iowait\",mode!=\"steal\"}[5m]),1)) )) *100) or (sum(avg_over_time(node_cpu_average{instance=\"$host\", cpu=\"All\",mode!=\"total\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"wait\",mode!=\"steal\"}[$interval])) or sum(avg_over_time(node_cpu_average{instance=\"$host\",cpu=\"All\",mode!=\"total\",mode!=\"idle\",mode!=\"user\",mode!=\"system\",mode!=\"wait\",mode!=\"steal\"}[5m])))),100)"
    }
   ]
  },
  { "title": "Copyrights & Legal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
   "content": "<center >\n  <p>MySQL and InnoDB are trademarks of Oracle Corp. Proudly running Percona Server. Copyright © 2006-2018 Percona LLC.</p>\n  <div style=\"text-align:center;\">\n    <a href=\"https://percona.com/terms-use\" style=\"display: inline;\">Terms of Use</a> | \n    <a href=\"https://percona.com/privacy-policy\" style=\"display: inline;\">Privacy</a> | \n    <a href=\"https://percona.com/copyright-policy\" style=\"display: inline;\">Copyright</a> | \n    <a href=\"https://percona.com/legal\" style=\"display: inline;\">Legal</a>\n  </div>\n</center>\n<hr>\n<link rel=\"stylesheet\" type=\"text/css\" href=\"//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css\" />\n<script src=\"//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js\"></script>\n<script>\nfunction bbb(){\n  \n  setTimeout(function (){ \n  window.cookieconsent.initialise({\n    \"palette\": {\n      \"popup\": {\n        \"background\": \"#eb6c44\",\n        \"text\": \"#ffffff\"\n      },\n      \"button\": {\n        \"background\": \"#f5d948\"\n      }\n    },\n    \"theme\": \"classic\",\n    \"content\": {\n      \"message\": \"This site uses cookies and other tracking technologies to assist with navigation, analyze your use of our products and services, assist with promotional and marketing efforts, allow you to give feedback, and provide content from third parties. If you do not want to accept cookies, adjust your browser settings to deny cookies or exit this site.\",\n      \"dismiss\": \"Allow cookies\",\n      \"link\": \"Cookie Policy\",\n      \"href\": \"https://www.percona.com/cookie-policy\"\n    }\n  })},3000)};\n  \n  \n  window.addEventListener(\"load\",bbb());\n\n\n\n</script>"
  }
 ]
}