{
 "title": "Home Dashboard",
 "tags": [
  "Percona",
  "Insight"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values({__name__=~\"node_load1|process_start_time_seconds\"}, instance)"
   }
  ]
 },
 "panels": [
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "content": "<br>\n<div class=\"text-center dashboard-header\">\n<img src=\"public/img/pmm-logo.svg\" height=\"60px\" width=\"60px\">\n  <span>Percona Monitoring and Management</span>\n</div>"
  },
  { "title": "General information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "type": "text",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "content": "**Overview**  \n[Percona Monitoring and Management (PMM)](https://www.percona.com/pmm) is a free and open-source platform for managing and monitoring MySQL and MongoDB performance, and provides time-based analysis to ensure that your data works as efficiently as possible. \n\n**Documentation**  \nPlease consult the official [PMM documentation](https://www.percona.com/doc/percona-monitoring-and-management/index.html) to learn more about PMM. Also of interest are the [Release notes](https://www.percona.com/doc/percona-monitoring-and-management/release-notes/index.html) and [FAQ](https://www.percona.com/doc/percona-monitoring-and-management/faq.html) for common questions about PMM.\n\n**Community and Blogs**  \nOn the [PMM Community Forums](https://www.percona.com/forums/questions-discussions/percona-monitoring-and-management) you will find help from Perconians and the Community at large.  Further, we publish PMM announcements and use cases regularly on the [Percona Database Performance Blog](https://www.percona.com/blog/category/percona-monitoring-and-management/)  \n\n**Get Help from Percona**  \nAre you looking for assistance that comes with a response-time guarantee? Let our [Support team](https://www.percona.com/services/support?utm_source=pmm&utm_medium=web&utm_campaign=support_link)  help you!\nAlready a customer? Log in to your [Percona Support Portal](https://customers.percona.com) \n\n\n\n"
  },
  {
   "title": "Starred and Recently used Dashboards",
   "type": "dashlist",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 5 }
  },
  {
   "title": "Systems under monitoring",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 5 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "count(node_memory_MemTotal{})" }
   ]
  },
  {
   "title": "Monitored DB Instances",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 7 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "count(mysql_global_status_uptime{} or mongodb_mongod_instance_uptime_seconds {})"
    }
   ]
  },
  {
   "type": "pmm-update-panel",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 9 },
   "targets": [
    {}
   ]
  },
  { "title": "Environment Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  { "title": "Host", "type": "text", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 15 }, "content": "<b>All</b>" },
  {
   "title": "CPU Busy",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by () ((sum by (instance,cpu) ( (clamp_max(rate(node_cpu{instance=~\"$host\",mode!='idle',mode!=\"iowait\"}[$interval]),1)) or  (clamp_max(irate(node_cpu{instance=~\"$host\",mode!='idle',mode!=\"iowait\"}[5m]),1)) ))*100 or (avg_over_time(node_cpu_average{instance=~\"$host\", mode=\"total\"}[$interval]) or avg_over_time(node_cpu_average{instance=~\"$host\", mode=\"total\"}[5m])))"
    }
   ]
  },
  {
   "title": "Mem Avail",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 15 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg by () ((node_memory_MemAvailable{instance=~\"$host\"} or (node_memory_MemFree{instance=~\"$host\"} + node_memory_Buffers{instance=~\"$host\"} + node_memory_Cached{instance=~\"$host\"})) / node_memory_MemTotal{instance=~\"$host\"}) * 100"
    }
   ]
  },
  {
   "title": "Disk Reads",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 15 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum by () (rate(node_vmstat_pgpgin{instance=~\"$host\"}[$interval]) or irate(node_vmstat_pgpgin{instance=~\"$host\"}[5m])) * 1024"
    }
   ]
  },
  {
   "title": "Disk Writes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 15 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum by () (rate(node_vmstat_pgpgout{instance=~\"$host\"}[$interval]) or irate(node_vmstat_pgpgout{instance=~\"$host\"}[5m])) * 1024"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 15 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum(rate(node_network_receive_bytes{instance=~\"$host\",device!=\"lo\"}[$interval]) \nor irate(node_network_receive_bytes{instance=~\"$host\",device!=\"lo\"}[5m]) \nor max_over_time(rdsosmetrics_network_rx{instance=~\"$host\"}[$interval]) \nor max_over_time(rdsosmetrics_network_rx{instance=~\"$host\"}[5m]))\n+\nsum(rate(node_network_transmit_bytes{instance=~\"$host\",device!=\"lo\"}[$interval]) \nor irate(node_network_transmit_bytes{instance=~\"$host\",device!=\"lo\"}[5m])\nor max_over_time(rdsosmetrics_network_tx{instance=~\"$host\"}[$interval]) \nor max_over_time(rdsosmetrics_network_tx{instance=~\"$host\"}[5m]))"
    }
   ]
  },
  {
   "title": "DB Conns",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 15 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum by () (max_over_time(mysql_global_status_threads_connected{instance=~\"$host\"}[$interval]) or max_over_time(mongodb_mongod_connections{instance=~\"$host\",state=\"current\"}[$interval]))"
    }
   ]
  },
  {
   "title": "DB QPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 15 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "sum by () (rate(mysql_global_status_queries{instance=~\"$host\"}[$interval]) or irate(mysql_global_status_queries{instance=~\"$host\"}[5m])) or (sum(rate(mongodb_mongod_op_counters_total{instance=~\"$host\",type!=\"command\"}[$interval])) or sum(irate(mongodb_mongod_op_counters_total{instance=~\"$host\",type!=\"command\"}[5m])))"
    }
   ]
  },
  {
   "title": "Virtual CPUs",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 15 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(node_cpu{instance=~\"$host\",mode=\"user\"} or rdsosmetrics_General_numVCPUs{instance=~\"$host\"})"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 15 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum by () (node_memory_MemTotal{instance=~\"$host\"})"
    }
   ]
  },
  {
   "title": "Host uptime",
   "type": "singlestat",
   "description": "AVG   Uptime for  `All`",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 15 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(node_time{instance=~\"$host\"} - node_boot_time{instance=~\"$host\"})"
    }
   ]
  },
  {
   "title": "DB uptime",
   "type": "singlestat",
   "description": "AVG for  `All`",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 15 },
   "format": "s",
   "valueName": "avg",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "avg(mysql_global_status_uptime{instance=~\"$host\"} or mongodb_mongod_instance_uptime_seconds {instance=~\"$host\"})"
    }
   ]
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 }, "repeat": "host" },
  { "type": "text", "gridPos": { "h": 3, "w": 2, "x": 0, "y": 19 }, "content": "$host" },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 19 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "clamp_max(avg by (instance) \n(sum by (cpu) ( (clamp_max(rate(node_cpu{instance=~\"$host\",mode!='idle',mode!=\"iowait\"}[$interval]),1)) or\n(clamp_max(irate(node_cpu{instance=~\"$host\",mode!='idle',mode!=\"iowait\"}[5m]),1)) )),1) *100 or\n(avg_over_time(node_cpu_average{instance=~\"$host\", mode=\"total\"}[$interval]) or\navg_over_time(node_cpu_average{instance=~\"$host\", mode=\"total\"}[5m]))"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 19 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "(node_memory_MemAvailable{instance=~\"$host\"} or \n(node_memory_MemFree{instance=~\"$host\"} + node_memory_Buffers{instance=~\"$host\"} + node_memory_Cached{instance=~\"$host\"})) / \nnode_memory_MemTotal{instance=~\"$host\"} * 100"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 19 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(node_vmstat_pgpgin{instance=~\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{instance=~\"$host\"}[5m]) * 1024"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 19 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "rate(node_vmstat_pgpgout{instance=~\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{instance=~\"$host\"}[5m]) * 1024"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 19 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "(sum(rate(node_network_receive_bytes{instance=~\"$host\", device!=\"lo\"}[$interval]) or\nirate(node_network_receive_bytes{instance=~\"$host\", device!=\"lo\"}[5m])) or \nsum(max_over_time(rdsosmetrics_network_rx{instance=~\"$host\"}[$interval])) or \nsum(max_over_time(rdsosmetrics_network_rx{instance=~\"$host\"}[5m]))) + \n(sum(rate(node_network_transmit_bytes{instance=~\"$host\", device!=\"lo\"}[$interval]) or \nirate(node_network_transmit_bytes{instance=~\"$host\", device!=\"lo\"}[5m])) or \nsum(max_over_time(rdsosmetrics_network_tx{instance=~\"$host\"}[$interval])) or \nsum(max_over_time(rdsosmetrics_network_tx{instance=~\"$host\"}[5m]))) "
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 19 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "(max_over_time(mysql_global_status_threads_connected{instance=~\"$host\"}[$interval]) or \nmax_over_time(mysql_global_status_threads_connected{instance=~\"$host\"}[5m])) or\n(max_over_time(mongodb_mongod_connections{instance=~\"$host\", state=\"current\"}[$interval]) or\nmax_over_time(mongodb_mongod_connections{instance=~\"$host\", state=\"current\"}[5m]))"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 19 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "(rate(mysql_global_status_queries{instance=~\"$host\"}[$interval]) or \nirate(mysql_global_status_queries{instance=~\"$host\"}[5m])) or \n(sum(rate(mongodb_mongod_op_counters_total{instance=~\"$host\", type!=\"command\"}[$interval])) or \nsum(irate(mongodb_mongod_op_counters_total{instance=~\"$host\", type!=\"command\"}[5m])))"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 19 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(node_cpu{mode=\"user\", instance=~\"$host\"}) or count(rdsosmetrics_General_numVCPUs{instance=~\"$host\"})"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 19 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=~\"$host\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 20, "y": 19 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "node_time{instance=~\"$host\"} - node_boot_time{instance=~\"$host\"}"
    }
   ]
  },
  {
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 22, "y": 19 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_status_uptime{instance=~\"$host\"} or mongodb_mongod_instance_uptime_seconds {instance=~\"$host\"}"
    }
   ]
  },
  { "title": "Copyrights & Legal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 990 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 991 },
   "content": "<center >\n  <p>MySQL and InnoDB are trademarks of Oracle Corp. Proudly running Percona Server. Copyright © 2006-2018 Percona LLC.</p>\n  <div style=\"text-align:center;\">\n    <a href=\"https://percona.com/terms-use\" style=\"display: inline;\">Terms of Use</a> | \n    <a href=\"https://percona.com/privacy-policy\" style=\"display: inline;\">Privacy</a> | \n    <a href=\"https://percona.com/copyright-policy\" style=\"display: inline;\">Copyright</a> | \n    <a href=\"https://percona.com/legal\" style=\"display: inline;\">Legal</a>\n  </div>\n</center>\n<hr>\n<link rel=\"stylesheet\" type=\"text/css\" href=\"//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css\" />\n<script src=\"//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js\"></script>\n<script>\nfunction bbb(){\n  \n  setTimeout(function (){ \n  window.cookieconsent.initialise({\n    \"palette\": {\n      \"popup\": {\n        \"background\": \"#eb6c44\",\n        \"text\": \"#ffffff\"\n      },\n      \"button\": {\n        \"background\": \"#f5d948\"\n      }\n    },\n    \"theme\": \"classic\",\n    \"content\": {\n      \"message\": \"This site uses cookies and other tracking technologies to assist with navigation, analyze your use of our products and services, assist with promotional and marketing efforts, allow you to give feedback, and provide content from third parties. If you do not want to accept cookies, adjust your browser settings to deny cookies or exit this site.\",\n      \"dismiss\": \"Allow cookies\",\n      \"link\": \"Cookie Policy\",\n      \"href\": \"https://www.percona.com/cookie-policy\"\n    }\n  })},3000)};\n  \n  \n  window.addEventListener(\"load\",bbb());\n\n\n\n</script>"
  }
 ]
}