{
 "title": "MySQL MyRocks Metrics",
 "tags": [
  "Percona",
  "MySQL"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(mysql_global_variables_rocksdb_block_cache_size, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "MyRocks  Cache",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_block_cache_hit{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_hit{instance=\"$host\"}[5m])",
     "legendFormat": "Hit"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_block_cache_miss{instance=\"$host\"}[$interval]) or  irate(mysql_global_status_rocksdb_block_cache_miss{instance=\"$host\"}[5m])",
     "legendFormat": "Miss"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_block_cache_add{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_add{instance=\"$host\"}[5m])",
     "legendFormat": "Added"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_block_cache_add_failures{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_add_failures{instance=\"$host\"}[5m])",
     "legendFormat": "Added Failures"
    }
   ]
  },
  {
   "title": "MyRocks Cache Data Bytes R/W",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_rocksdb_block_cache_bytes_read{instance=\"$host\"}[$interval])  or irate(mysql_global_status_rocksdb_block_cache_bytes_read{instance=\"$host\"}[5m]) ",
     "legendFormat": "Reads"
    },
    {
     "expr": "rate(mysql_global_status_rocksdb_block_cache_bytes_write{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_bytes_write{instance=\"$host\"}[5m])",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "MyRocks Cache Index Hit Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_block_cache_index_hit{instance=\"$host\"}[$interval])  or irate(mysql_global_status_rocksdb_block_cache_index_hit{instance=\"$host\"}[5m]) ",
     "legendFormat": "Hit"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_block_cache_index_miss{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_index_miss{instance=\"$host\"}[5m])",
     "legendFormat": "Miss"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_block_cache_index_add{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_index_add{instance=\"$host\"}[5m])",
     "legendFormat": "Added"
    }
   ]
  },
  {
   "title": "MyRocks Cache Index",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_block_cache_index_bytes_insert{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_index_bytes_insert{instance=\"$host\"}[5m])",
     "legendFormat": "Inserted"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_block_cache_index_bytes_evict{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_index_bytes_evict{instance=\"$host\"}[5m])",
     "legendFormat": "Evicted"
    }
   ]
  },
  {
   "title": "MyRocks Cache Filter Hit Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_block_cache_filter_hit{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_filter_hit{instance=\"$host\"}[5m])",
     "legendFormat": "Hit"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_block_cache_filter_miss{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_filter_miss{instance=\"$host\"}[5m])",
     "legendFormat": "Miss"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_block_cache_filter_add{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_filter_add{instance=\"$host\"}[5m])",
     "legendFormat": "Added"
    }
   ]
  },
  {
   "title": "MyRocks Cache Filter",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_block_cache_filter_bytes_insert{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_filter_bytes_insert{instance=\"$host\"}[5m])",
     "legendFormat": "Inserted"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_block_cache_filter_bytes_evict{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_filter_bytes_evict{instance=\"$host\"}[5m])",
     "legendFormat": "Evicted"
    }
   ]
  },
  {
   "title": "MyRocks Cache Data Bytes Inserted",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_rocksdb_block_cache_data_bytes_insert{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_block_cache_data_bytes_insert{instance=\"$host\"}[5m])",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "MyRocks Bloom Filter",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_rocksdb_bloom_filter_useful{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_bloom_filter_useful{instance=\"$host\"}[5m]) ",
     "legendFormat": "Useful"
    }
   ]
  },
  {
   "title": "MyRocks Memtable",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_memtable_hit{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_memtable_hit{instance=\"$host\"}[5m])",
     "legendFormat": "Hit"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_memtable_miss{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_memtable_miss{instance=\"$host\"}[5m])",
     "legendFormat": "Miss"
    }
   ]
  },
  {
   "title": "MyRocks Cache l0/l1",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_get_hit_l0{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_get_hit_l0{instance=\"$host\"}[5m]) ",
     "legendFormat": "l0"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_get_hit_l1{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_get_hit_l1{instance=\"$host\"}[5m])",
     "legendFormat": "l1"
    }
   ]
  },
  {
   "title": "MyRocks Number Of Keys",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_number_keys_read{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_number_keys_read{instance=\"$host\"}[5m])",
     "legendFormat": "Read"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_number_keys_written{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_number_keys_written{instance=\"$host\"}[5m])",
     "legendFormat": "Write"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_number_keys_updated{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_number_keys_updated{instance=\"$host\"}[5m])",
     "legendFormat": "Updated"
    }
   ]
  },
  {
   "title": "MyRocks R/W",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_bytes_read{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_bytes_read{instance=\"$host\"}[5m])",
     "legendFormat": "Read"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_bytes_written{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_bytes_written{instance=\"$host\"}[5m])",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "MyRocks Number of DB ops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_number_db_seek{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_number_db_seek{instance=\"$host\"}[5m])",
     "legendFormat": "Seek"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_number_db_seek_found{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_number_db_seek_found{instance=\"$host\"}[5m])",
     "legendFormat": "Seek Found"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_number_db_next{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_number_db_next{instance=\"$host\"}[5m])",
     "legendFormat": "Next"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_number_db_next_found{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_number_db_next_found{instance=\"$host\"}[5m])",
     "legendFormat": "Next Found"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_number_db_prev{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_number_db_prev{instance=\"$host\"}[5m])",
     "legendFormat": "Prev"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_number_db_prev_found{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_number_db_prev_found{instance=\"$host\"}[5m])",
     "legendFormat": "Prev Found"
    }
   ]
  },
  {
   "title": "MyRocks Write ops",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_write_self{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_write_self{instance=\"$host\"}[5m])",
     "legendFormat": "Self"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_write_other{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_write_other{instance=\"$host\"}[5m])",
     "legendFormat": "Other"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_write_timeout{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_write_timeout{instance=\"$host\"}[5m]) ",
     "legendFormat": "Timeout"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_write_wal{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_write_wal{instance=\"$host\"}[5m]) ",
     "legendFormat": "WAL"
    }
   ]
  },
  {
   "title": "MyRocks Bytes Read by Iterations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_rocksdb_iter_bytes_read{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_iter_bytes_read{instance=\"$host\"}[5m])",
     "legendFormat": "Reads"
    }
   ]
  },
  {
   "title": "MyRocks Number Reseeks in Iterations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_rocksdb_number_reseeks_iteration{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_number_reseeks_iteration{instance=\"$host\"}[5m])",
     "legendFormat": "Reseeks"
    }
   ]
  },
  {
   "title": "MyRocks WAL",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_wal_synced{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_wal_synced{instance=\"$host\"}[5m]) ",
     "legendFormat": "Syncs"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_wal_bytes{instance=\"$host\"}[$interval])  or irate(mysql_global_status_rocksdb_wal_bytes{instance=\"$host\"}[5m]) ",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "MyRocks File Operations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_no_file_opens{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_no_file_opens{instance=\"$host\"}[5m]) ",
     "legendFormat": "Open"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_no_file_closes{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_no_file_closes{instance=\"$host\"}[5m])",
     "legendFormat": "Closes"
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_rocksdb_no_file_errors{instance=\"$host\"}[$interval]) or irate(mysql_global_status_rocksdb_no_file_errors{instance=\"$host\"}[5m]) ",
     "legendFormat": "Errors"
    }
   ]
  },
  { "title": "Copyrights & Legal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 91 },
   "content": "<center >\n  <p>MySQL and InnoDB are trademarks of Oracle Corp. Proudly running Percona Server. Copyright © 2006-2018 Percona LLC.</p>\n  <div style=\"text-align:center;\">\n    <a href=\"https://percona.com/terms-use\" style=\"display: inline;\">Terms of Use</a> | \n    <a href=\"https://percona.com/privacy-policy\" style=\"display: inline;\">Privacy</a> | \n    <a href=\"https://percona.com/copyright-policy\" style=\"display: inline;\">Copyright</a> | \n    <a href=\"https://percona.com/legal\" style=\"display: inline;\">Legal</a>\n  </div>\n</center>\n<hr>\n<link rel=\"stylesheet\" type=\"text/css\" href=\"//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css\" />\n<script src=\"//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js\"></script>\n<script>\nfunction bbb(){\n  \n  setTimeout(function (){ \n  window.cookieconsent.initialise({\n    \"palette\": {\n      \"popup\": {\n        \"background\": \"#eb6c44\",\n        \"text\": \"#ffffff\"\n      },\n      \"button\": {\n        \"background\": \"#f5d948\"\n      }\n    },\n    \"theme\": \"classic\",\n    \"content\": {\n      \"message\": \"This site uses cookies and other tracking technologies to assist with navigation, analyze your use of our products and services, assist with promotional and marketing efforts, allow you to give feedback, and provide content from third parties. If you do not want to accept cookies, adjust your browser settings to deny cookies or exit this site.\",\n      \"dismiss\": \"Allow cookies\",\n      \"link\": \"Cookie Policy\",\n      \"href\": \"https://www.percona.com/cookie-policy\"\n    }\n  })},3000)};\n  \n  \n  window.addEventListener(\"load\",bbb());\n\n\n\n</script>"
  }
 ]
}