{
 "title": "MySQL TokuDB Metrics",
 "tags": [
  "MySQL",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(mysql_global_variables_tokudb_cache_size, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "TokuDB Checkpointing",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_tokudb_leaf_nodes_flushed_checkpoint_bytes{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_nodes_flushed_checkpoint_bytes{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_leaf_nodes_flushed_checkpoint_bytes"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_checkpoint_bytes{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_checkpoint_bytes{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_nonleaf_nodes_flushed_to_disk_checkpoint_bytes"
    }
   ]
  },
  {
   "title": "TokuDB Cache Size",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "mysql_global_variables_tokudb_cache_size{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "TokuDB CacheTable",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_tokudb_cachetable_miss{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_cachetable_miss{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_cachetable_miss"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_cachetable_evictions{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_cachetable_evictions{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_cachetable_evictions"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_cachetable_prefetches{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_cachetable_prefetches{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_cachetable_prefetches"
    }
   ]
  },
  {
   "title": "TokuDB CacheTable Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "{__name__=~\"mysql_global_status_tokudb_cachetable_size_.+\", instance=\"$host\"}",
     "legendFormat": "{{ __name__ }}"
    }
   ]
  },
  {
   "title": "TokuDB Pivots Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_tokudb_pivots_fetched_for_query_seconds{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_pivots_fetched_for_query_seconds{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_pivots_fetched_for_query_seconds"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_pivots_fetched_for_prefetch_seconds{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_pivots_fetched_for_prefetch_seconds{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_pivots_fetched_for_prefetch_seconds"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_pivots_fetched_for_write_seconds{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_pivots_fetched_for_write_seconds{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_pivots_fetched_for_write_seconds"
    }
   ]
  },
  {
   "title": "TokuDB Opens/Closes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_tokudb_db_opens{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_db_opens{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_db_opens"
    },
    {
     "expr": "mysql_global_status_tokudb_db_open_current{instance=\"$host\"}",
     "legendFormat": "tokudb_db_open_current"
    },
    {
     "expr": "mysql_global_status_tokudb_db_open_max{instance=\"$host\"}",
     "legendFormat": "tokudb_db_open_max"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_db_closes{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_db_closes{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_db_closes"
    }
   ]
  },
  {
   "title": "TokuDB Leaf",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_tokudb_leaf_compression_to_memory_seconds{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_compression_to_memory_seconds{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_leaf_compression_to_memory_seconds"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_leaf_serialization_to_memory_seconds{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_serialization_to_memory_seconds{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_leaf_serialization_to_memory_seconds"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_leaf_deserialization_to_memory_seconds{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_deserialization_to_memory_seconds{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_leaf_deserialization_to_memory_seconds"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_leaf_decompression_to_memory_seconds{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_decompression_to_memory_seconds{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_leaf_decompression_to_memory_seconds"
    }
   ]
  },
  {
   "title": "TokuDB NonLeaf",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_tokudb_nonleaf_compression_to_memory_seconds{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_compression_to_memory_seconds{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_nonleaf_compression_to_memory_seconds"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_nonleaf_serialization_to_memory_seconds{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_serialization_to_memory_seconds{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_nonleaf_serialization_to_memory_seconds"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_nonleaf_deserialization_to_memory_seconds{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_deserialization_to_memory_seconds{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_nonleaf_deserialization_to_memory_seconds"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_nonleaf_decompression_to_memory_seconds{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_decompression_to_memory_seconds{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_nonleaf_decompression_to_memory_seconds"
    }
   ]
  },
  {
   "title": "TokuDB Basements Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_tokudb_basements_fetched_target_query_seconds{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_basements_fetched_target_query_seconds{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_basements_fetched_target_query_seconds"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_basements_fetched_prefetch_seconds{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_basements_fetched_prefetch_seconds{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_basements_fetched_prefetch_seconds"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_basements_fetched_prelocked_range_seconds{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_basements_fetched_prelocked_range_seconds{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_basements_fetched_prelocked_range_seconds"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_basements_fetched_for_write_seconds{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_basements_fetched_for_write_seconds{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_basements_fetched_for_write_seconds"
    }
   ]
  },
  {
   "title": "TokuDB Promotion Injections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_tokudb_promotion_injections_at_depth_0{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_promotion_injections_at_depth_0{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_promotion_injections_at_depth_0"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_promotion_injections_at_depth_1{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_promotion_injections_at_depth_1{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_promotion_injections_at_depth_1"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_promotion_injections_at_depth_2{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_promotion_injections_at_depth_2{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_promotion_injections_at_depth_2"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_promotion_injections_at_depth_3{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_promotion_injections_at_depth_3{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_promotion_injections_at_depth_3"
    }
   ]
  },
  {
   "title": "TokuDB Promotion Stopped",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_tokudb_promotion_stopped_nonempty_buffer{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_promotion_stopped_nonempty_buffer{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_promotion_stopped_nonempty_buffer"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_promotion_stopped_at_height_1{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_promotion_stopped_at_height_1{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_promotion_stopped_at_height_1"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_promotion_stopped_child_locked_or_not_in_memory{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_promotion_stopped_child_locked_or_not_in_memory{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_promotion_stopped_child_locked_or_not_in_memory"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_promotion_stopped_child_not_fully_in_memory{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_promotion_stopped_child_not_fully_in_memory{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_promotion_stopped_child_not_fully_in_memory"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_promotion_stopped_after_locking_child{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_promotion_stopped_after_locking_child{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_promotion_stopped_after_locking_child"
    }
   ]
  },
  {
   "title": "TokuDB Promotion Root",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_tokudb_promotion_roots_split{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_promotion_roots_split{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_promotion_roots_split"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_promotion_h1_roots_injected_into{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_promotion_h1_roots_injected_into{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_promotion_h1_roots_injected_into"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_promotion_leaf_roots_injected_into{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_promotion_leaf_roots_injected_into{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_promotion_leaf_roots_injected_into"
    }
   ]
  },
  {
   "title": "TokuDB Buffers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_tokudb_buffers_fetched_target_query{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_buffers_fetched_target_query{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_buffers_fetched_target_query"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_buffers_fetched_prefetch{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_buffers_fetched_prefetch{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_buffers_fetched_prefetch"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_buffers_fetched_prelocked_range{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_buffers_fetched_prelocked_range{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_buffers_fetched_prelocked_range"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_buffers_fetched_for_write{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_buffers_fetched_for_write{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_buffers_fetched_for_write"
    }
   ]
  },
  {
   "title": "TokuDB Buffers Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_tokudb_buffers_fetched_target_query_seconds{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_buffers_fetched_target_query_seconds{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_buffers_fetched_target_query_seconds"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_buffers_fetched_prefetch_seconds{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_buffers_fetched_prefetch_seconds{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_buffers_fetched_prefetch_seconds"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_buffers_fetched_prelocked_range_seconds{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_buffers_fetched_prelocked_range_seconds{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_buffers_fetched_prelocked_range_seconds"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_buffers_fetched_for_write_seconds{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_buffers_fetched_for_write_seconds{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_buffers_fetched_for_write_seconds"
    }
   ]
  },
  {
   "title": "TokuDB Flushed Not Checkpoint",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_tokudb_leaf_nodes_flushed_not_checkpoint_bytes{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_nodes_flushed_not_checkpoint_bytes{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_leaf_nodes_flushed_not_checkpoint_bytes"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_leaf_nodes_flushed_not_checkpoint_uncompressed_bytes{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_nodes_flushed_not_checkpoint_uncompressed_bytes{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_leaf_nodes_flushed_not_checkpoint_uncompressed_bytes"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_not_checkpoint_bytes{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_not_checkpoint_bytes{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_nonleaf_nodes_flushed_to_disk_not_checkpoint_bytes"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_not_checkpoint_uncompresse{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_not_checkpoint_uncompresse{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_nonleaf_nodes_flushed_to_disk_not_checkpoint_uncompresse"
    }
   ]
  },
  {
   "title": "TokuDB Logger",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_tokudb_logger_writes_bytes{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_logger_writes_bytes{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_logger_writes_bytes"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_logger_writes_seconds{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_logger_writes_seconds{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_logger_writes_seconds"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_logger_writes{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_logger_writes{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_logger_writes"
    }
   ]
  },
  {
   "title": "TokuDB Create and Destroy",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_tokudb_leaf_nodes_created{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_nodes_created{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_leaf_nodes_created"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_nonleaf_nodes_created{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_nodes_created{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_nonleaf_nodes_created"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_leaf_nodes_destroyed{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_nodes_destroyed{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_leaf_nodes_destroyed"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_nonleaf_nodes_destroyed{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_nodes_destroyed{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_nonleaf_nodes_destroyed"
    }
   ]
  },
  {
   "title": "TokuDB Messages",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 77 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_tokudb_messages_injected_at_root_bytes{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_messages_injected_at_root_bytes{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_messages_injected_at_root_bytes"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_messages_in_trees_estimate_bytes{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_messages_in_trees_estimate_bytes{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_messages_in_trees_estimate_bytes"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_messages_flushed_from_h1_to_leaves_bytes{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_messages_flushed_from_h1_to_leaves_bytes{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_messages_flushed_from_h1_to_leaves_bytes"
    }
   ]
  },
  {
   "title": "TokuDB Messages Ignored",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_tokudb_messages_ignored_by_leaf_due_to_msn{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_messages_ignored_by_leaf_due_to_msn{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_messages_ignored_by_leaf_due_to_msn"
    }
   ]
  },
  {
   "title": "TokuDB Garbage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 84 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_tokudb_cursor_skip_deleted_leaf_entry{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_cursor_skip_deleted_leaf_entry{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_cursor_skip_deleted_leaf_entry"
    }
   ]
  },
  {
   "title": "TokuDB Flush Types Time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 91 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_tokudb_leaf_nodes_flushed_checkpoint_seconds{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_nodes_flushed_checkpoint_seconds{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_leaf_nodes_flushed_checkpoint_seconds"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_checkpoint_seconds{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_checkpoint_seconds{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_nonleaf_nodes_flushed_to_disk_checkpoint_seconds"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_leaf_nodes_flushed_not_checkpoint_seconds{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_leaf_nodes_flushed_not_checkpoint_seconds{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_leaf_nodes_flushed_not_checkpoint_seconds"
    },
    {
     "expr": "rate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_not_checkpoint_seconds{instance=\"$host\"}[$interval]) or irate(mysql_global_status_tokudb_nonleaf_nodes_flushed_to_disk_not_checkpoint_seconds{instance=\"$host\"}[5m])",
     "legendFormat": "tokudb_nonleaf_nodes_flushed_to_disk_not_checkpoint_seconds"
    }
   ]
  },
  {
   "title": "TokuDB Compression Ratios",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 98 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "mysql_global_status_tokudb_overall_node_compression_ratio{instance=\"$host\"} or i",
     "legendFormat": "tokudb_overall_node_compression_ratio"
    },
    {
     "expr": "mysql_global_status_tokudb_leaf_node_compression_ratio{instance=\"$host\"}",
     "legendFormat": "tokudb_leaf_node_compression_ratio"
    },
    {
     "expr": "mysql_global_status_tokudb_nonleaf_node_compression_ratio{instance=\"$host\"}",
     "legendFormat": "tokudb_nonleaf_node_compression_ratio"
    }
   ]
  },
  { "title": "Copyrights & Legal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 990 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 991 },
   "content": "<center >\n  <p>MySQL and InnoDB are trademarks of Oracle Corp. Proudly running Percona Server. Copyright © 2006-2018 Percona LLC.</p>\n  <div style=\"text-align:center;\">\n    <a href=\"https://percona.com/terms-use\" style=\"display: inline;\">Terms of Use</a> | \n    <a href=\"https://percona.com/privacy-policy\" style=\"display: inline;\">Privacy</a> | \n    <a href=\"https://percona.com/copyright-policy\" style=\"display: inline;\">Copyright</a> | \n    <a href=\"https://percona.com/legal\" style=\"display: inline;\">Legal</a>\n  </div>\n</center>\n<hr>\n<link rel=\"stylesheet\" type=\"text/css\" href=\"//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css\" />\n<script src=\"//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js\"></script>\n<script>\nfunction bbb(){\n  \n  setTimeout(function (){ \n  window.cookieconsent.initialise({\n    \"palette\": {\n      \"popup\": {\n        \"background\": \"#eb6c44\",\n        \"text\": \"#ffffff\"\n      },\n      \"button\": {\n        \"background\": \"#f5d948\"\n      }\n    },\n    \"theme\": \"classic\",\n    \"content\": {\n      \"message\": \"This site uses cookies and other tracking technologies to assist with navigation, analyze your use of our products and services, assist with promotional and marketing efforts, allow you to give feedback, and provide content from third parties. If you do not want to accept cookies, adjust your browser settings to deny cookies or exit this site.\",\n      \"dismiss\": \"Allow cookies\",\n      \"link\": \"Cookie Policy\",\n      \"href\": \"https://www.percona.com/cookie-policy\"\n    }\n  })},3000)};\n  \n  \n  window.addEventListener(\"load\",bbb());\n\n\n\n</script>"
  }
 ]
}