{
 "title": "MySQL Amazon Aurora Metrics",
 "tags": [
  "Percona",
  "MySQL"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(mysql_global_variables_aurora_lab_mode, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Amazon Aurora Transaction Commits",
   "type": "graph",
   "description": "This graph shows number of Commits which Amazon Aurora engine performed as well as average commit latency.   Graph Latency does not always correlates with number of commits performed and can quite high in certain situations.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_auroradb_commits{instance=\"$host\"}[$interval]) or irate(mysql_global_status_auroradb_commits{instance=\"$host\"}[5m])",
     "legendFormat": "Number of Amazon Aurora Commits "
    },
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_auroradb_commit_latency{instance=\"$host\"}[$interval])/rate(mysql_global_status_auroradb_commits{instance=\"$host\"}[$interval]) or irate(mysql_global_status_auroradb_commit_latency{instance=\"$host\"}[5m])/irate(mysql_global_status_auroradb_commits{instance=\"$host\"}[5m])",
     "legendFormat": "Amazon Aurora Commit avg Latency"
    }
   ]
  },
  {
   "title": "Amazon Aurora Load",
   "type": "graph",
   "description": "This graph shows us what statements contribute most load on the system as well as what load corresponds to Amazon Aurora transaction commit.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(mysql_global_status_auroradb_commit_latency{instance=\"$host\"}[$interval])/1000000 or irate(mysql_global_status_auroradb_commit_latency{instance=\"$host\"}[5m])/1000000",
     "legendFormat": "Write Transaction Commit Load"
    },
    {
     "expr": "rate(mysql_global_status_auroradb_ddl_stmt_duration{instance=\"$host\"}[$interval])/1000000 or irate(mysql_global_status_auroradb_ddl_stmt_duration{instance=\"$host\"}[5m])/1000000",
     "legendFormat": "DDL Load"
    },
    {
     "expr": "rate(mysql_global_status_auroradb_select_stmt_duration{instance=\"$host\"}[$interval])/1000000 or irate(mysql_global_status_auroradb_select_stmt_duration{instance=\"$host\"}[5m])/1000000",
     "legendFormat": "SELECT load "
    },
    {
     "expr": "rate(mysql_global_status_auroradb_insert_stmt_duration{instance=\"$host\"}[$interval])/1000000 or irate(mysql_global_status_auroradb_insert_stmt_duration{instance=\"$host\"}[5m])/1000000",
     "legendFormat": "INSERT load"
    },
    {
     "expr": "rate(mysql_global_status_auroradb_update_stmt_duration{instance=\"$host\"}[$interval])/1000000 or irate(mysql_global_status_auroradb_update_stmt_duration{instance=\"$host\"}[5m])/1000000",
     "legendFormat": "UPDATE load"
    },
    {
     "expr": "rate(mysql_global_status_auroradb_delete_stmt_duration{instance=\"$host\"}[$interval])/1000000 or irate(mysql_global_status_auroradb_delete_stmt_duration{instance=\"$host\"}[5m])/1000000",
     "legendFormat": "DELETE load"
    }
   ]
  },
  {
   "title": "Aurora Memory Used",
   "type": "graph",
   "description": "This graph shows how much memory is used by Amazon Aurora lock manager as well as amount of memory used by Amazon Aurora to store Data Dictionary.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_aurora_lockmgr_memory_used{instance=\"$host\"}",
     "legendFormat": "Aurora Lock Manager Memory"
    },
    {
     "calculatedInterval": "2m",
     "expr": "mysql_global_status_aurora_dict_sys_mem_size{instance=\"$host\"}",
     "legendFormat": "Aurora Dictionary Memory "
    }
   ]
  },
  {
   "title": "Amazon Aurora Statement Latency",
   "type": "graph",
   "description": "This graph shows average latency for most important types of statements.   Latency spikes are often indicative of the instance overload.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "(rate(mysql_global_status_auroradb_ddl_stmt_duration{instance=\"$host\"}[$interval])/ (sum(rate(mysql_global_status_commands_total{instance=\"$host\",command=~'alter_table|create_index|drop_index|drop_table'}[$interval])) without(command)))",
     "legendFormat": "DDL Latency"
    },
    {
     "expr": "(rate(mysql_global_status_auroradb_select_stmt_duration{instance=\"$host\"}[$interval])/ (sum(rate(mysql_global_status_commands_total{instance=\"$host\",command='select'}[$interval])) without(command))+rate(mysql_global_status_qcache_hits{instance=\"$host\"}[$interval]))",
     "legendFormat": "SELECT Latency"
    },
    {
     "expr": "(rate(mysql_global_status_auroradb_insert_stmt_duration{instance=\"$host\"}[$interval])/ (sum(rate(mysql_global_status_commands_total{instance=\"$host\",command=~'insert|insert_select'}[$interval])) without(command)))",
     "legendFormat": "INSERT Latency"
    },
    {
     "expr": "(rate(mysql_global_status_auroradb_update_stmt_duration{instance=\"$host\"}[$interval])/ (sum(rate(mysql_global_status_commands_total{instance=\"$host\",command=~'update|update_multi'}[$interval])) without(command)))",
     "legendFormat": "UPDATE Latency"
    },
    {
     "expr": "(rate(mysql_global_status_auroradb_delete_stmt_duration{instance=\"$host\"}[$interval])/ (sum(rate(mysql_global_status_commands_total{instance=\"$host\",command=~'delete|delete_multi'}[$interval])) without(command)))",
     "legendFormat": "DELETE Latency"
    }
   ]
  },
  {
   "title": "Amazon Aurora Special Command Counters",
   "type": "graph",
   "description": "Amazon Aurora MySQL allows number of commands which are not available in standard MySQL. This graph shows usage of such commands.  Regular “unit_test” calls can be seen in default Amazon Aurora install,  the rest will depend on your workload.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_commands_total{instance=\"$host\",command=~'awslambda|alter_system|unit_test|show_volume_status'}[$interval])",
     "legendFormat": "{{command}}"
    }
   ]
  },
  {
   "title": "Amazon Aurora Problems",
   "type": "graph",
   "description": "This graph shows different kinds of Internal Amazon Aurora MySQL Problems which general should be zero in normal operation.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(mysql_global_status_auroradb_thread_deadlocks{instance=\"$host\"}[$interval])",
     "legendFormat": "Thread Deadlocks"
    },
    {
     "expr": "rate(mysql_global_status_aurora_missing_history_on_replica_incidents{instance=\"$host\"}[$interval])",
     "legendFormat": "Missing History on Replica Incidents"
    },
    {
     "expr": "rate(mysql_global_status_aurora_reserved_mem_exceeded_incidents{instance=\"$host\"}[$interval])",
     "legendFormat": "Reserved Mem Exceeded Incidents"
    }
   ]
  },
  { "title": "Copyrights & Legal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 90 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 91 },
   "content": "<center >\n  <p>MySQL and InnoDB are trademarks of Oracle Corp. Proudly running Percona Server. Copyright © 2006-2018 Percona LLC.</p>\n  <div style=\"text-align:center;\">\n    <a href=\"https://percona.com/terms-use\" style=\"display: inline;\">Terms of Use</a> | \n    <a href=\"https://percona.com/privacy-policy\" style=\"display: inline;\">Privacy</a> | \n    <a href=\"https://percona.com/copyright-policy\" style=\"display: inline;\">Copyright</a> | \n    <a href=\"https://percona.com/legal\" style=\"display: inline;\">Legal</a>\n  </div>\n</center>\n<hr>\n<link rel=\"stylesheet\" type=\"text/css\" href=\"//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css\" />\n<script src=\"//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js\"></script>\n<script>\nfunction bbb(){\n  \n  setTimeout(function (){ \n  window.cookieconsent.initialise({\n    \"palette\": {\n      \"popup\": {\n        \"background\": \"#eb6c44\",\n        \"text\": \"#ffffff\"\n      },\n      \"button\": {\n        \"background\": \"#f5d948\"\n      }\n    },\n    \"theme\": \"classic\",\n    \"content\": {\n      \"message\": \"This site uses cookies and other tracking technologies to assist with navigation, analyze your use of our products and services, assist with promotional and marketing efforts, allow you to give feedback, and provide content from third parties. If you do not want to accept cookies, adjust your browse\",\n      \"dismiss\": \"Allow cookies\",\n      \"link\": \"Cookie Policy\",\n      \"href\": \"https://www.percona.com/cookie-policy\"\n    }\n  })},3000)};\n  \n  \n  window.addEventListener(\"load\",bbb());\n\n\n\n</script>"
  }
 ]
}