{
 "title": "Prometheus",
 "tags": [
  "Insight",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  { "title": "Prometheus Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(rate(process_cpu_seconds_total{job=\"prometheus\"}[$interval])) by () or sum(irate(process_cpu_seconds_total{job=\"prometheus\"}[5m])) by ()) / count(node_cpu{mode=\"user\", instance=\"pmm-server\"})*100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "100*sum(go_memstats_alloc_bytes{job=\"prometheus\"}+go_memstats_stack_inuse_bytes{job=\"prometheus\"}) by () / sum(node_memory_MemTotal{instance=\"pmm-server\"}) by ()"
    }
   ]
  },
  {
   "title": "Urgency Score",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "max_over_time(prometheus_local_storage_persistence_urgency_score[$interval]) or max_over_time(prometheus_local_storage_persistence_urgency_score[5m])"
    }
   ]
  },
  {
   "title": "Samples Ingested",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(prometheus_local_storage_ingested_samples_total[$interval]) or irate(prometheus_local_storage_ingested_samples_total[5m])"
    }
   ]
  },
  {
   "title": "Scrapes Performed",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "format": "ops",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(prometheus_target_interval_length_seconds_count[$interval])) or sum(irate(prometheus_target_interval_length_seconds_count[5m]))"
    }
   ]
  },
  {
   "title": "Time Series in Memory",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "prometheus_local_storage_memory_series"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prometheus Process CPU Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 9 },
     "yaxes": [
      { "format": "none" }
     ],
     "targets": [
      {
       "expr": "rate(process_cpu_seconds_total{job=\"prometheus\"}[$interval]) or irate(process_cpu_seconds_total{job=\"prometheus\"}[5m])",
       "legendFormat": "CPU Cores Used"
      },
      {
       "expr": "count(node_cpu{mode=\"user\", instance=\"pmm-server\"})",
       "legendFormat": "CPU Cores Total"
      },
      {
       "expr": "count(node_cpu{mode=\"user\", instance=\"pmm-server\"})*0.75",
       "legendFormat": "Recommended Limit"
      }
     ]
    },
    {
     "title": "Prometheus Process  Memory Usage",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 9 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job=\"prometheus\"}",
       "legendFormat": "Resident Memory"
      },
      {
       "expr": "process_virtual_memory_bytes{job=\"prometheus\"}",
       "legendFormat": "Virtual Memory"
      },
      {
       "expr": "go_memstats_alloc_bytes{job=\"prometheus\"}+go_memstats_stack_inuse_bytes{job=\"prometheus\"}",
       "legendFormat": "Go Memory Allocated and In Use"
      },
      {
       "expr": "prometheus_local_storage_target_heap_size_bytes{job=\"prometheus\"}",
       "legendFormat": "Configured Target Storage Heap Size"
      },
      {
       "expr": "node_memory_MemTotal{instance=\"pmm-server\"}",
       "legendFormat": "Total System Memory"
      }
     ]
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Time Series",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "prometheus_local_storage_memory_series{instance=~\"pmm-server|prometheus\"}",
       "legendFormat": "Time Series in Memory"
      },
      {
       "expr": "prometheus_local_storage_open_head_chunks{instance=~\"pmm-server|prometheus\"}",
       "legendFormat": "Open Heads Chunks"
      },
      {
       "expr": "prometheus_local_storage_memory_dirty_series{instance=~\"pmm-server|prometheus\"}",
       "legendFormat": "Dirty Time Series"
      }
     ]
    },
    {
     "title": "Local Storage Urgency Score",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max_over_time(prometheus_local_storage_persistence_urgency_score[$interval]) or max_over_time(prometheus_local_storage_persistence_urgency_score[5m])",
       "legendFormat": "Urgency Score "
      },
      { "expr": "0.8", "legendFormat": "Rushed Mode High Watermark" },
      { "expr": "0.7", "legendFormat": "Rushed Mode Low Watermark" }
     ]
    },
    {
     "title": "Prometheus Problems",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_local_storage_persist_errors_total[$interval])  or irate(prometheus_local_storage_persist_errors_total[5m]) ",
       "legendFormat": "Storage Errors "
      },
      {
       "expr": "max_over_time(prometheus_local_storage_rushed_mode[$interval]) or max_over_time(prometheus_local_storage_rushed_mode[5m])",
       "legendFormat": "Has been in Rushed Mode"
      },
      {
       "expr": "prometheus_local_storage_inconsistencies_total",
       "legendFormat": "Storage Inconsitencies Discovered since Start"
      },
      {
       "expr": "rate(prometheus_target_skipped_scrapes_total[$interval]) or rate(prometheus_target_skipped_scrapes_total[5m])",
       "legendFormat": "Scrapes Skipped (Possible Storge Overload)"
      }
     ]
    },
    {
     "title": "Prometheus Checkpointing",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_local_storage_checkpointing{instance=~\"pmm-server|prometheus\"}[$interval]) or irate(prometheus_local_storage_checkpointing{instance=~\"pmm-server|prometheus\"}[5m])",
       "legendFormat": "Percent of Time Checkpoint is Active"
      },
      {
       "expr": "rate(prometheus_local_storage_checkpoint_duration_seconds_count{instance=~\"pmm-server|prometheus\"}[$interval]) or irate(prometheus_local_storage_checkpoint_duration_seconds_count{instance=~\"pmm-server|prometheus\"}[5m])",
       "legendFormat": "Number of Checkpoints Performed"
      },
      {
       "expr": "rate(prometheus_local_storage_checkpoint_series_chunks_written_sum{instance=~\"pmm-server|prometheus\"}[$interval]) or irate(prometheus_local_storage_checkpoint_series_chunks_written_sum{instance=~\"pmm-server|prometheus\"}[5m])",
       "legendFormat": "Chunks Written by Checkpointing"
      }
     ]
    },
    {
     "title": "Prometheus Out of Order Samples",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_local_storage_out_of_order_samples_total{instance=~\"pmm-server|prometheus\"}[$interval]) or irate(prometheus_local_storage_out_of_order_samples_total{instance=~\"pmm-server|prometheus\"}[5m])",
       "legendFormat": " {{reason}} - Samples Out of Order "
      }
     ]
    },
    {
     "title": "Chunks Memory Details",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "prometheus_local_storage_chunks_to_persist",
       "legendFormat": "Chunks not yet Persisted"
      },
      {
       "expr": "prometheus_local_storage_memory_chunks",
       "legendFormat": "Chunks Held in Memory"
      },
      {
       "expr": "prometheus_local_storage_memory_chunks-(prometheus_local_storage_chunks_to_persist+prometheus_local_storage_open_head_chunks)",
       "legendFormat": "Evictable Chunks"
      }
     ]
    },
    {
     "title": "Series Operations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_local_storage_series_ops_total{job=\"prometheus\"}[$interval]) or irate(prometheus_local_storage_series_ops_total{job=\"prometheus\"}[5m])",
       "legendFormat": "{{type}} - Series Ops "
      }
     ]
    },
    {
     "title": "Prometheus Storage Operations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_local_storage_chunk_ops_total{instance=~\"pmm-server|prometheus\"}[$interval]) or irate(prometheus_local_storage_chunk_ops_total{instance=~\"pmm-server|prometheus\"}[5m])",
       "legendFormat": "{{type}} - Chunk Operations "
      },
      {
       "expr": "rate(prometheus_local_storage_chunkdesc_ops_total{instance=~\"pmm-server|prometheus\"}[$interval]) or irate(prometheus_local_storage_chunkdesc_ops_total{instance=~\"pmm-server|prometheus\"}[5m])",
       "legendFormat": "{{type}} - ChunkDesc Operations "
      }
     ]
    },
    {
     "title": "ChunkDesc Memory Details",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "prometheus_local_storage_memory_chunkdescs",
       "legendFormat": "ChunkDescs Held in Memory"
      }
     ]
    }
   ]
  },
  {
   "title": "Scraping",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Ingestion",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_local_storage_ingested_samples_total[$interval]) or irate(prometheus_local_storage_ingested_samples_total[5m])",
       "legendFormat": "Samples Ingested"
      },
      {
       "expr": "sum(rate(prometheus_target_interval_length_seconds_count[$interval])) or sum(irate(prometheus_target_interval_length_seconds_count[5m]))",
       "legendFormat": "Scrapes Performed"
      }
     ]
    },
    {
     "title": "Prometheus Targets",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "count(up)", "legendFormat": "Targets Configured" },
      {
       "expr": "sum(avg_over_time(up[$interval])) or  sum(avg_over_time(up[5m]))",
       "legendFormat": "Avg Succesfully Scraped Targets"
      },
      {
       "expr": "sum(min_over_time(up[$interval])) or  sum(min_over_time(up[5m]))",
       "legendFormat": "Min Successfully Scraped Targets"
      }
     ]
    },
    {
     "title": "Scraped Target by Job",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(avg_over_time(up[$interval])) by (job) or sum(avg_over_time(up[5m])) by (job)",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Scrape Time by Job",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(avg_over_time(scrape_duration_seconds[$interval])) by (job) or avg(avg_over_time(scrape_duration_seconds[5m])) by (job) ",
       "legendFormat": "{{job}}"
      }
     ]
    },
    {
     "title": "Scraped Target by Instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(avg_over_time(up[$interval])) by (instance) or sum(avg_over_time(up[5m])) by (instance)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Scrape Time by Instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 53 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "avg(avg_over_time(scrape_duration_seconds[$interval])) by (instance) or avg(avg_over_time(scrape_duration_seconds[5m])) by (instance) ",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Scrapes by Target Frequency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_target_interval_length_seconds_count[$interval]) or irate(prometheus_target_interval_length_seconds_count[5m])",
       "legendFormat": "Rate of {{interval}} scrapes"
      }
     ]
    },
    {
     "title": "Scrape Frequency Versus Target",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(rate(prometheus_target_interval_length_seconds_sum[$interval]) / rate(prometheus_target_interval_length_seconds_count[$interval])) or (irate(prometheus_target_interval_length_seconds_sum[5m]) / irate(prometheus_target_interval_length_seconds_count[5m]))",
       "legendFormat": "Actual  {{interval}} scrape interval  length"
      }
     ]
    },
    {
     "title": "Scraping Time Drift",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 67 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      { "expr": "time() - node_time", "legendFormat": "{{instance}}" }
     ]
    },
    {
     "title": "Prometheus Scrape Interval Variance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 67 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(sum(prometheus_target_interval_length_seconds{instance=~\"pmm-server|prometheus\",interval=\"1s\",job=\"prometheus\",quantile=\"0.99\"}) by () - sum(prometheus_target_interval_length_seconds{instance=~\"pmm-server|prometheus\",interval=\"1s\",job=\"prometheus\",quantile=\"0.01\"}) by ())/1",
       "legendFormat": "1sec  Target Interval Variance"
      },
      {
       "expr": "(sum(prometheus_target_interval_length_seconds{instance=~\"pmm-server|prometheus\",interval=\"5s\",job=\"prometheus\",quantile=\"0.99\"}) by () - sum(prometheus_target_interval_length_seconds{instance=~\"pmm-server|prometheus\",interval=\"5s\",job=\"prometheus\",quantile=\"0.01\"}) by ())/5",
       "legendFormat": "5sec Target Interval Variance"
      },
      {
       "expr": "(sum(prometheus_target_interval_length_seconds{instance=~\"pmm-server|prometheus\",interval=\"1m0s\",job=\"prometheus\",quantile=\"0.99\"}) by () - sum(prometheus_target_interval_length_seconds{instance=~\"pmm-server|prometheus\",interval=\"1m0s\",job=\"prometheus\",quantile=\"0.01\"}) by ())/60",
       "legendFormat": "1min Target Interval Variance"
      }
     ]
    },
    {
     "title": "Slowest Jobs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 74 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(10,max_over_time(scrape_duration_seconds[$interval]) or max_over_time(scrape_duration_seconds[5m]))",
       "legendFormat": "{{job}} at {{instance}}"
      }
     ]
    },
    {
     "title": "Largest Samples Jobs",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 74 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10,max_over_time(scrape_samples_scraped[$interval]) or max_over_time(scrape_duration_seconds[5m]))",
       "legendFormat": "{{job}} at {{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Queries",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prometheus Queries",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 75 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg_over_time(prometheus_engine_queries[$interval]) or avg_over_time(prometheus_engine_queries[5m])",
       "legendFormat": "Avg Queries Active"
      },
      {
       "expr": "max_over_time(prometheus_engine_queries[$interval]) or max_over_time(prometheus_engine_queries[5m])",
       "legendFormat": "Max Queries Active"
      },
      {
       "expr": "prometheus_engine_queries_concurrent_max",
       "legendFormat": "Maximum Queries Permitted"
      }
     ]
    },
    {
     "title": "Prometheus Query Execution",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 75 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_engine_query_duration_seconds_count[$interval]) or irate(prometheus_engine_query_duration_seconds_count[$interval]) ",
       "legendFormat": "{{slice}} - Executed"
      }
     ]
    },
    {
     "title": "Prometheus Query Execution Latency",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 82 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "(rate(prometheus_engine_query_duration_seconds_sum[$interval])/rate(prometheus_engine_query_duration_seconds_count[$interval])) or (irate(prometheus_engine_query_duration_seconds_sum[$interval])/irate(prometheus_engine_query_duration_seconds_count[$interval]))",
       "legendFormat": "{{slice}} - Avg Time"
      }
     ]
    },
    {
     "title": "Prometheus Query Execution Load",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 82 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(prometheus_engine_query_duration_seconds_sum[$interval])",
       "legendFormat": "{{slice}} - Load"
      }
     ]
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "HTTP Requests by Handler",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{job=\"prometheus\"}[$interval])) by (handler) or sum(irate(http_requests_total{job=\"prometheus\"}[5m])) by (handler)",
     "legendFormat": "{{ handler }}"
    }
   ]
  },
  {
   "title": "HTTP Errors",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "rate(http_requests_total{job=\"prometheus\",code!=\"200\"}[$interval])  or irate(http_requests_total{job=\"prometheus\",code!=\"200\"}[5m])  ",
     "legendFormat": "{{code}} on {{handler}}"
    }
   ]
  },
  {
   "title": "HTTP Avg Response time by Handler",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "rate(http_request_duration_microseconds_sum{instance=~\"pmm-server|prometheus\"}[$interval])/rate(http_request_duration_microseconds_count{instance=~\"pmm-server|prometheus\"}[$interval])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "HTTP 99% Percentile Response time by Handler",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "http_request_duration_microseconds{instance=~\"pmm-server|prometheus\",quantile=\"0.99\"}",
     "legendFormat": "{{handler}} - 99% response time"
    }
   ]
  },
  {
   "title": "HTTP Response Average Size by Handler",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(http_response_size_bytes_sum[$interval])/rate(http_response_size_bytes_count[$interval])",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "HTTP 99% Percentile Response Size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "http_response_size_bytes{instance=~\"pmm-server|prometheus\",quantile=\"0.99\"}",
     "legendFormat": "{{handler}} - 99% response size"
    }
   ]
  },
  {
   "title": "Time Series Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top 10 metrics by time series count",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 111 },
     "targets": [
      {
       "expr": "topk(10, count({__name__=~\".+\"})  by (__name__))",
       "legendFormat": "{{ __name__ }}"
      }
     ]
    },
    {
     "title": "Top 10 hosts by time series count",
     "type": "table",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 111 },
     "targets": [
      {
       "expr": "topk(10, count({__name__=~\".+\"})  by (instance))",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "System Level Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Busy",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 0, "y": 112 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "clamp_max(avg by (instance) (sum by () ( (clamp_max(rate(node_cpu{instance=\"pmm-server\",mode!='idle',mode!=\"iowait\"}[$interval]),1)) or  (clamp_max(irate(node_cpu{instance=\"pmm-server\",mode!='idle',mode!=\"iowait\"}[5m]),1)) )),1) *100"
      }
     ]
    },
    {
     "title": "Mem Avail",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 4, "y": 112 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "(node_memory_MemAvailable{instance=\"pmm-server\"} or (node_memory_MemFree{instance=\"pmm-server\"} + node_memory_Buffers{instance=\"pmm-server\"} + node_memory_Cached{instance=\"pmm-server\"})) / node_memory_MemTotal{instance=\"pmm-server\"} * 100"
      }
     ]
    },
    {
     "title": "Disk Reads",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 8, "y": 112 },
     "format": "Bps",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "rate(node_vmstat_pgpgin{instance=\"pmm-server\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{instance=\"pmm-server\"}[5m]) * 1024"
      }
     ]
    },
    {
     "title": "Disk Writes",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 12, "y": 112 },
     "format": "Bps",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "rate(node_vmstat_pgpgout{instance=\"pmm-server\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{instance=\"pmm-server\"}[5m]) * 1024"
      }
     ]
    },
    {
     "title": "Network IO",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 16, "y": 112 },
     "format": "Bps",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "(sum(rate(node_network_receive_bytes{instance=\"pmm-server\", device!=\"lo\"}[$interval]) or irate(node_network_receive_bytes{instance=\"pmm-server\", device!=\"lo\"}[5m]))) + (sum(rate(node_network_transmit_bytes{instance=\"pmm-server\", device!=\"lo\"}[$interval]) or irate(node_network_transmit_bytes{instance=\"pmm-server\", device!=\"lo\"}[5m])))"
      }
     ]
    },
    {
     "title": "Sys Uptime",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 4, "x": 20, "y": 112 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "node_time{instance=\"pmm-server\"} - node_boot_time{instance=\"pmm-server\"}"
      }
     ]
    }
   ]
  },
  { "title": "PMM Server Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 40 },
   "content": "To simplify problem detection, you can download <a href=\"/managed/logs.zip\">server logs</a>. Please include this file if you are submitting a bug report   "
  },
  { "title": "Copyrights & Legal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 990 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 991 },
   "content": "<center >\n  <p>MySQL and InnoDB are trademarks of Oracle Corp. Proudly running Percona Server. Copyright © 2006-2018 Percona LLC.</p>\n  <div style=\"text-align:center;\">\n    <a href=\"https://percona.com/terms-use\" style=\"display: inline;\">Terms of Use</a> | \n    <a href=\"https://percona.com/privacy-policy\" style=\"display: inline;\">Privacy</a> | \n    <a href=\"https://percona.com/copyright-policy\" style=\"display: inline;\">Copyright</a> | \n    <a href=\"https://percona.com/legal\" style=\"display: inline;\">Legal</a>\n  </div>\n</center>\n<hr>\n<link rel=\"stylesheet\" type=\"text/css\" href=\"//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css\" />\n<script src=\"//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js\"></script>\n<script>\nfunction bbb(){\n  \n  setTimeout(function (){ \n  window.cookieconsent.initialise({\n    \"palette\": {\n      \"popup\": {\n        \"background\": \"#eb6c44\",\n        \"text\": \"#ffffff\"\n      },\n      \"button\": {\n        \"background\": \"#f5d948\"\n      }\n    },\n    \"theme\": \"classic\",\n    \"content\": {\n      \"message\": \"This site uses cookies and other tracking technologies to assist with navigation, analyze your use of our products and services, assist with promotional and marketing efforts, allow you to give feedback, and provide content from third parties. If you do not want to accept cookies, adjust your browse\",\n      \"dismiss\": \"Allow cookies\",\n      \"link\": \"Cookie Policy\",\n      \"href\": \"https://www.percona.com/cookie-policy\"\n    }\n  })},3000)};\n  \n  \n  window.addEventListener(\"load\",bbb());\n\n\n\n</script>"
  }
 ]
}