{
 "title": "Prometheus Exporter Status",
 "tags": [
  "Insight",
  "Percona"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values({__name__=~\"node_load1|process_start_time_seconds\"}, instance)"
   }
  ]
 },
 "panels": [
  { "title": "Node Exporter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "(sum(rate(process_cpu_seconds_total{instance=\"$host\",job=\"linux\"}[$interval])) by () or sum(irate(process_cpu_seconds_total{instance=\"$host\",job=\"linux\"}[5m])) by ()) / count(node_cpu{mode=\"user\", instance=\"$host\"})*100"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "process_resident_memory_bytes{instance=\"$host\",job=\"linux\"}"
    }
   ]
  },
  {
   "title": "File Descriptors Used",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "process_open_fds{instance=\"$host\",job=\"linux\"}"
    }
   ]
  },
  {
   "title": "Exporter Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "time() - process_start_time_seconds{instance=\"$host\",job=\"linux\"}"
    }
   ]
  },
  {
   "title": "Collector Scrape Successful",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "min_over_time(node_scrape_collector_success{instance=\"$host\"}[$interval]) or min_over_time(node_scrape_collector_success{instance=\"$host\"}[5m])",
     "legendFormat": "{{collector}}"
    }
   ]
  },
  {
   "title": "Collector Execution Time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "avg_over_time(node_scrape_collector_duration_seconds{instance=\"$host\"}[$interval]) or avg_over_time(node_scrape_collector_duration_seconds{instance=\"$host\"}[5m])",
     "legendFormat": "{{collector}}"
    }
   ]
  },
  {
   "title": "MySQLd Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 10 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "expr": "(sum(rate(process_cpu_seconds_total{instance=\"$host\",job=\"mysql\"}[$interval])) by () or sum(irate(process_cpu_seconds_total{instance=\"$host\",job=\"mysql\"}[5m])) by ()) / count(node_cpu{mode=\"user\", instance=\"$host\"})*100"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 10 },
     "format": "bytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_resident_memory_bytes{instance=\"$host\",job=\"mysql\"}"
      }
     ]
    },
    {
     "title": "File Descriptors Used",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 10 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "expr": "process_open_fds{instance=\"$host\",job=\"mysql\"}"
      }
     ]
    },
    {
     "title": "Exporter Uptime",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 10 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "expr": "time() - process_start_time_seconds{instance=\"$host\",job=\"mysql\"}"
      }
     ]
    },
    {
     "title": "Collector Execution Time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "avg_over_time(mysql_exporter_collector_duration_seconds{instance=\"$host\"}[$interval]) or avg_over_time(mysql_exporter_collector_duration_seconds{instance=\"$host\"}[5m])",
       "legendFormat": "{{collector}}"
      }
     ]
    },
    {
     "title": "MySQLd Exporter Errors",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "max_over_time(mysql_exporter_hr_last_scrape_error{instance=\"$host\"}[$interval]) or max_over_time(mysql_exporter_hr_last_scrape_error{instance=\"$host\"}[5m])",
       "legendFormat": "High Resolution"
      },
      {
       "expr": "max_over_time(mysql_exporter_mr_last_scrape_error{instance=\"$host\"}[$interval]) or max_over_time(mysql_exporter_mr_last_scrape_error{instance=\"$host\"}[5m])",
       "legendFormat": "Medium Resolution"
      },
      {
       "expr": "max_over_time(mysql_exporter_lr_last_scrape_error{instance=\"$host\"}[$interval]) or max_over_time(mysql_exporter_lr_last_scrape_error{instance=\"$host\"}[5m])",
       "legendFormat": "Low Resolution"
      }
     ]
    },
    {
     "title": "Rate of  Scrapes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "rate(mysql_exporter_hr_scrapes_total{instance=\"$host\"}[$interval]) or irate(mysql_exporter_hr_scrapes_total{instance=\"$host\"}[5m])",
       "legendFormat": "High Resolution"
      },
      {
       "expr": "rate(mysql_exporter_mr_scrapes_total{instance=\"$host\"}[$interval]) or irate(mysql_exporter_mr_scrapes_total{instance=\"$host\"}[5m])",
       "legendFormat": "Medium Resolution"
      },
      {
       "expr": "rate(mysql_exporter_lr_scrapes_total{instance=\"$host\"}[$interval]) or irate(mysql_exporter_lr_scrapes_total{instance=\"$host\"}[5m])",
       "legendFormat": "Low Resolution"
      }
     ]
    },
    {
     "title": "MySQL up",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "min_over_time(mysql_up{instance=\"$host\"}[$interval]) or min_over_time(mysql_up{instance=\"$host\"}[5m])",
       "legendFormat": "MySQL Up"
      }
     ]
    }
   ]
  },
  {
   "title": "MongoDB Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 18 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "(sum(rate(process_cpu_seconds_total{instance=\"$host\",job=\"mongodb\"}[$interval])) by () or sum(irate(process_cpu_seconds_total{instance=\"$host\",job=\"mongodb\"}[5m])) by ()) / count(node_cpu{mode=\"user\", instance=\"$host\"})*100"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 18 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "process_resident_memory_bytes{instance=\"$host\",job=\"mongodb\"}"
      }
     ]
    },
    {
     "title": "File Descriptors Used",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 18 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "process_open_fds{instance=\"$host\",job=\"mongodb\"}"
      }
     ]
    },
    {
     "title": "Exporter Uptime",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 18 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "time() - process_start_time_seconds{instance=\"$host\",job=\"mongodb\"}"
      }
     ]
    },
    {
     "title": "MongoDB Scrape Performance",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "avg_over_time(mongodb_exporter_last_scrape_duration_seconds{instance=\"$host\"}[$interval]) or avg_over_time(mongodb_exporter_last_scrape_duration_seconds{instance=\"$host\"}[5m])",
       "legendFormat": "Avg Scrape Time"
      }
     ]
    },
    {
     "title": "MongoDB Exporter Errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "max_over_time(mongodb_exporter_last_scrape_error{instance=\"$host\"}[$interval]) or max_over_time(mongodb_exporter_last_scrape_error{instance=\"$host\"}[5m])",
       "legendFormat": "MongoDB Exporter Errors"
      }
     ]
    },
    {
     "title": "Rate of  Scrapes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "rate(mongodb_exporter_scrapes_total{instance=\"$host\"}[$interval]) or irate(mongodb_exporter_scrapes_total{instance=\"$host\"}[5m])",
       "legendFormat": "Scrapes Rate"
      }
     ]
    },
    {
     "title": "MongoDB up",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "min_over_time(mongodb_up{instance=\"$host\"}[$interval]) or min_over_time(mongodb_up{instance=\"$host\"}[5m])",
       "legendFormat": "MongoDB Up"
      }
     ]
    }
   ]
  },
  {
   "title": "ProxySQL Exporter",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Usage",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 0, "y": 27 },
     "format": "percent",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "(sum(rate(process_cpu_seconds_total{instance=\"$host\",job=\"proxysql\"}[$interval])) by () or sum(irate(process_cpu_seconds_total{instance=\"$host\",job=\"proxysql\"}[5m])) by ()) / count(node_cpu{mode=\"user\", instance=\"$host\"})*100"
      }
     ]
    },
    {
     "title": "Memory Usage",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 6, "y": 27 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "process_resident_memory_bytes{instance=\"$host\",job=\"proxysql\"}"
      }
     ]
    },
    {
     "title": "File Descriptors Used",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 12, "y": 27 },
     "format": "short",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "process_open_fds{instance=\"$host\",job=\"proxysql\"}"
      }
     ]
    },
    {
     "title": "Exporter Uptime",
     "type": "singlestat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 27 },
     "format": "s",
     "valueName": "current",
     "targets": [
      {
       "calculatedInterval": "10m",
       "expr": "time() - process_start_time_seconds{instance=\"$host\",job=\"proxysql\"}"
      }
     ]
    },
    {
     "title": "ProxySQL Scrape Performance",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "avg_over_time(proxysql_exporter_last_scrape_duration_seconds{instance=\"$host\"}[$interval]) or avg_over_time(proxysql_exporter_last_scrape_duration_seconds{instance=\"$host\"}[5m])",
       "legendFormat": "Avg Scrape Time"
      }
     ]
    },
    {
     "title": "ProxySQL Exporter Errors",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "max_over_time(proxysql_exporter_last_scrape_error{instance=\"$host\"}[$interval]) or max_over_time(proxysql_exporter_last_scrape_error{instance=\"$host\"}[5m])",
       "legendFormat": "ProxySQL Exporter Errors"
      }
     ]
    },
    {
     "title": "Rate of  Scrapes",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "rate(proxysql_exporter_scrapes_total{instance=\"$host\"}[$interval]) or irate(proxysql_exporter_scrapes_total{instance=\"$host\"}[5m])",
       "legendFormat": "Scrapes Rate"
      }
     ]
    },
    {
     "title": "ProxySQL up",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "calculatedInterval": "10s",
       "expr": "min_over_time(proxysql_up{instance=\"$host\"}[$interval]) or min_over_time(proxysql_up{instance=\"$host\"}[5m])",
       "legendFormat": "ProxySQL Up"
      }
     ]
    }
   ]
  },
  { "title": "Copyrights & Legal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 990 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 991 },
   "content": "<center >\n  <p>MySQL and InnoDB are trademarks of Oracle Corp. Proudly running Percona Server. Copyright © 2006-2018 Percona LLC.</p>\n  <div style=\"text-align:center;\">\n    <a href=\"https://percona.com/terms-use\" style=\"display: inline;\">Terms of Use</a> | \n    <a href=\"https://percona.com/privacy-policy\" style=\"display: inline;\">Privacy</a> | \n    <a href=\"https://percona.com/copyright-policy\" style=\"display: inline;\">Copyright</a> | \n    <a href=\"https://percona.com/legal\" style=\"display: inline;\">Legal</a>\n  </div>\n</center>\n<hr>\n<link rel=\"stylesheet\" type=\"text/css\" href=\"//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css\" />\n<script src=\"//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js\"></script>\n<script>\nfunction bbb(){\n  \n  setTimeout(function (){ \n  window.cookieconsent.initialise({\n    \"palette\": {\n      \"popup\": {\n        \"background\": \"#eb6c44\",\n        \"text\": \"#ffffff\"\n      },\n      \"button\": {\n        \"background\": \"#f5d948\"\n      }\n    },\n    \"theme\": \"classic\",\n    \"content\": {\n      \"message\": \"This site uses cookies and other tracking technologies to assist with navigation, analyze your use of our products and services, assist with promotional and marketing efforts, allow you to give feedback, and provide content from third parties. If you do not want to accept cookies, adjust your browse\",\n      \"dismiss\": \"Allow cookies\",\n      \"link\": \"Cookie Policy\",\n      \"href\": \"https://www.percona.com/cookie-policy\"\n    }\n  })},3000)};\n  \n  \n  window.addEventListener(\"load\",bbb());\n\n\n\n</script>"
  }
 ]
}