{
 "title": "ProxySQL Overview",
 "tags": [
  "Percona",
  "HA"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "proxysql",
    "label": "ProxySQL Instance",
    "query": "label_values(proxysql_mysql_status_active_transactions, instance)"
   },
   {
    "name": "hostgroup",
    "label": "Hostgroup",
    "query": "label_values(proxysql_connection_pool_status{instance=\"$proxysql\"}, hostgroup)"
   }
  ]
 },
 "panels": [
  { "title": "ProxySQL Instance Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Hostgroup Size",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "scalar(count(proxysql_connection_pool_status{instance=\"$proxysql\", hostgroup=\"$hostgroup\"}))",
     "legendFormat": "Size"
    }
   ]
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Client Connections (All Host Groups)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "proxysql_mysql_status_client_connections_connected{instance=\"$proxysql\"}",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "Client Questions (All Host Groups)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(proxysql_mysql_status_questions{instance=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_questions{instance=\"$proxysql\"}[5m])",
     "legendFormat": "Question Rate"
    }
   ]
  },
  { "title": "Connection Pool Usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Endpoint Status",
   "type": "table",
   "gridPos": { "h": 7, "w": 18, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "proxysql_connection_pool_status{instance=\"$proxysql\", hostgroup=~\"$hostgroup\"}",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "content": "Status number to state mapping:\n\n1 `ONLINE`\n\n2 `SHUNNED`\n\n3 `OFFLINE_SOFT`\n\n4 `OFFLINE_HARD`\n\nFor status details, see the [description](https://github.com/sysown/proxysql/blob/master/doc/admin_tables.md#mysql_servers)."
  },
  { "title": "Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Active Backend Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "proxysql_connection_pool_conn_used{instance=\"$proxysql\", hostgroup=~\"$hostgroup\"}",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Failed Backend Connections",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(proxysql_connection_pool_conn_err{instance=\"$proxysql\", hostgroup=~\"$hostgroup\"}[$interval]) or irate(proxysql_connection_pool_conn_err{instance=\"$proxysql\", hostgroup=~\"$hostgroup\"}[5m])",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 } },
  {
   "title": "Queries Routed",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(proxysql_connection_pool_queries{instance=\"$proxysql\", hostgroup=~\"$hostgroup\"}[$interval]) or irate(proxysql_connection_pool_queries{instance=\"$proxysql\", hostgroup=~\"$hostgroup\"}[5m])",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Query processor time efficecy",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(proxysql_mysql_status_query_processor_time_nsec{instance=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_query_processor_time_nsec{instance=\"$proxysql\"}[5m]))/(rate(proxysql_mysql_status_questions{instance=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_questions{instance=\"$proxysql\"}[5m]))",
     "legendFormat": "QP_efficency_query"
    },
    {
     "expr": "(rate(proxysql_mysql_status_questions{instance=\"$proxysql\"}[$interval]) or irate(proxysql_mysql_status_questions{instance=\"$proxysql\"}[5m]))",
     "legendFormat": "Questions"
    }
   ]
  },
  { "title": "Queries", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 } },
  {
   "title": "Connection Free",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "proxysql_connection_pool_conn_free{instance=\"$proxysql\", hostgroup=~\"$hostgroup\"}",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 38 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "proxysql_connection_pool_latency_us{instance=\"$proxysql\", hostgroup=~\"$hostgroup\"}",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  { "title": "Query Cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Query Cache memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "proxysql_mysql_status_query_cache_memory_bytes{instance=\"$proxysql\"}",
     "legendFormat": "QC Total Memory used"
    },
    {
     "expr": "proxysql_mysql_status_query_cache_memory_bytes{instance=\"$proxysql\"}/proxysql_mysql_status_query_cache_entries{instance=\"$proxysql\"}",
     "legendFormat": "Bytes for cached query avg"
    }
   ]
  },
  {
   "title": "Query Cache efficiency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 46 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "((rate(proxysql_mysql_status_query_cache_count_get_ok{instance=\"$proxysql\"}[$interval]) + rate(proxysql_mysql_status_query_cache_count_get_ok{instance=\"$proxysql\"}[$interval])) or (irate(proxysql_mysql_status_query_cache_count_get_ok{instance=\"$proxysql\"}[5m]) + irate(proxysql_mysql_status_query_cache_count_get_ok{instance=\"$proxysql\"}[5m]))/(rate(proxysql_mysql_status_query_cache_count_get{instance=\"$proxysql\"}[$interval]) + rate(proxysql_mysql_status_query_cache_count_get{instance=\"$proxysql\"}[$interval])) or (irate(proxysql_mysql_status_query_cache_count_get{instance=\"$proxysql\"}[5m]) + irate(proxysql_mysql_status_query_cache_count_get{instance=\"$proxysql\"}[5m])))        ",
     "legendFormat": "Query Cache GET efficency"
    },
    {
     "expr": "((rate(proxysql_mysql_status_query_cache_bytes_out{instance=\"$proxysql\"}[$interval]) + rate(proxysql_mysql_status_query_cache_bytes_out{instance=\"$proxysql\"}[$interval])) or (irate(proxysql_mysql_status_query_cache_bytes_out{instance=\"$proxysql\"}[5m]) + irate(proxysql_mysql_status_query_cache_bytes_out{instance=\"$proxysql\"}[5m]))/(rate(proxysql_mysql_status_query_cache_bytes_in{instance=\"$proxysql\"}[$interval]) + rate(proxysql_mysql_status_query_cache_bytes_in{instance=\"$proxysql\"}[$interval])) or (irate(proxysql_mysql_status_query_cache_bytes_in{instance=\"$proxysql\"}[5m]) + irate(proxysql_mysql_status_query_cache_bytes_in{instance=\"$proxysql\"}[5m])))        ",
     "legendFormat": "Insert VS read efficency (high is good)"
    }
   ]
  },
  {
   "title": "Network Traffic and Mirroring efficency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 }
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "(rate(proxysql_connection_pool_bytes_data_recv{instance=\"$proxysql\", hostgroup=~\"$hostgroup\"}[$interval]) + rate(proxysql_connection_pool_bytes_data_sent{instance=\"$proxysql\", hostgroup=~\"$hostgroup\"}[$interval])) or (irate(proxysql_connection_pool_bytes_data_recv{instance=\"$proxysql\", hostgroup=~\"$hostgroup\"}[5m]) + irate(proxysql_connection_pool_bytes_data_sent{instance=\"$proxysql\", hostgroup=~\"$hostgroup\"}[5m]))",
     "legendFormat": "{{ endpoint }}"
    }
   ]
  },
  {
   "title": "Mirroring efficency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "proxysql_mysql_status_mirror_concurrency{instance=\"$proxysql\"}",
     "legendFormat": "Concurrent Mirror threads"
    },
    {
     "expr": "proxysql_mysql_status_mirror_queue_length{instance=\"$proxysql\"}",
     "legendFormat": "Mirror queue lenght (queries)"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 } },
  {
   "title": "Memory Utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "proxysql_mysql_status_query_cache_memory_bytes{instance=\"$proxysql\"}",
     "legendFormat": "Query Cache"
    },
    {
     "expr": "proxysql_mysql_status_sqlite3_memory_bytes{instance=\"$proxysql\"}",
     "legendFormat": "SQLite"
    },
    {
     "expr": "proxysql_mysql_status_connpool_memory_bytes{instance=\"$proxysql\"}",
     "legendFormat": "Connection Pool"
    }
   ]
  },
  { "title": "Copyrights & Legal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 990 } },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 991 },
   "content": "<center >\n  <p>MySQL and InnoDB are trademarks of Oracle Corp. Proudly running Percona Server. Copyright © 2006-2018 Percona LLC.</p>\n  <div style=\"text-align:center;\">\n    <a href=\"https://percona.com/terms-use\" style=\"display: inline;\">Terms of Use</a> | \n    <a href=\"https://percona.com/privacy-policy\" style=\"display: inline;\">Privacy</a> | \n    <a href=\"https://percona.com/copyright-policy\" style=\"display: inline;\">Copyright</a> | \n    <a href=\"https://percona.com/legal\" style=\"display: inline;\">Legal</a>\n  </div>\n</center>\n<hr>\n<link rel=\"stylesheet\" type=\"text/css\" href=\"//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.css\" />\n<script src=\"//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/3.0.3/cookieconsent.min.js\"></script>\n<script>\nfunction bbb(){\n  \n  setTimeout(function (){ \n  window.cookieconsent.initialise({\n    \"palette\": {\n      \"popup\": {\n        \"background\": \"#eb6c44\",\n        \"text\": \"#ffffff\"\n      },\n      \"button\": {\n        \"background\": \"#f5d948\"\n      }\n    },\n    \"theme\": \"classic\",\n    \"content\": {\n      \"message\": \"This site uses cookies and other tracking technologies to assist with navigation, analyze your use of our products and services, assist with promotional and marketing efforts, allow you to give feedback, and provide content from third parties. If you do not want to accept cookies, adjust your browser settings to deny cookies or exit this site.\",\n      \"dismiss\": \"Allow cookies\",\n      \"link\": \"Cookie Policy\",\n      \"href\": \"https://www.percona.com/cookie-policy\"\n    }\n  })},3000)};\n  \n  \n  window.addEventListener(\"load\",bbb());\n\n\n\n</script>"
  }
 ]
}